# Generated by Django 4.0 on 2022-01-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('productprice', models.FloatField()),
                ('productdesc', models.CharField(max_length=200)),
                ('productimage', models.ImageField(blank=True, upload_to='proimage/')),
            ],
        ),
    ]
