# Generated by Django 4.0 on 2022-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='questype',
            field=models.CharField(choices=[('WHICH TOWN DO U LIVE IN', 'which town do u live in'), ('HOBBY', 'hobby'), ('SPORTS', 'sports')], default='WHICH TOWN DO U LIVE IN', max_length=200),
        ),
    ]
