# Generated by Django 4.0 on 2022-01-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_account_answer_account_questype'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_price', models.FloatField(default=0)),
                ('pro_desc', models.CharField(max_length=200)),
                ('pro_image', models.ImageField(blank=True, upload_to='proimage/')),
                ('pro_qty', models.FloatField(default=1)),
            ],
        ),
    ]
