# Generated by Django 4.0 on 2022-01-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='useofcart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='pro_image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pro_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pro_qty',
            field=models.IntegerField(default=1),
        ),
    ]
